prod:
  image: vizzuality/python-skeleton-gdal-dask:1.0.0${STAGING}
  ports:
    - "5900"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: python-skeleton-gdal-dask${STAGING}
